### ISSUE TITLE
Exception: Invalid token when updating existing object

### ISSUE THREAD

**Issue by egreenspan2** [CheckPointSW/dynobj#1]
Attempting to update existing dynamic object, getting the following exception:

Traceback (most recent call last):
  File "dns2dyn.py", line 109, in <module>
    main()
  File "dns2dyn.py", line 105, in main
    manager.set_addresses(name, resolve(hosts))
  File "dynobj.py", line 287, in set_addresses
    self.clear_object(name)
  File "dynobj.py", line 231, in clear_object
    self._run(*params)
  File "dynobj.py", line 153, in _run
    _validate_token(param)
  File "dynobj.py", line 67, in _validate_token
    raise Exception('Invalid token:\n' + repr(token))
Exception: Invalid token:
u'172.217.6.106          172.217.6.106'

Steps to recreate:

./dns2dyn.py -f dynamic.json -s ssh -g <gateway> -u <user>

First run when the object does not exists, update is successful.

Second executing fails.

**Comment by chkp-ofer** [comment]
Fixed in 042d1ef
